CREATE DATABASE [Library]

CREATE TABLE Authors 
(
	AuthorId INT IDENTITY PRIMARY KEY,
	AuthorName VARCHAR(100) NOT NULL
)

CREATE TABLE Books 
(
	BookId INT IDENTITY(1,1) PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL,
	AuthorId INT FOREIGN KEY REFERENCES Authors
)

CREATE TABLE BookCount 
(
	BookId INT FOREIGN KEY REFERENCES Books,
	[Count] INT NOT NULL
)

CREATE TABLE Customers
(
	CustomerId INT IDENTITY(1,1) PRIMARY KEY,
	[Name] VARCHAR(100) NOT NULL,
)

CREATE TABLE BookHistory 
(
	BookId INT FOREIGN KEY REFERENCES Books,
	CustomerId INT FOREIGN KEY REFERENCES Customers,
	DateOfTaking DATE NOT NULL,
	DateReturne DATE NOT NULL
)